#!/bin/bash
if [ -z ${XDG_CONFIG_HOME+x} ]; \
    then config_dir="$HOME/.config/quibble"; echo "XDG_CONFIG_HOME is unset, attempting to clean $config_dir"; \
    else config_dir="$XDG_CONFIG_HOME/quibble"; echo "attempting to clean $config_dir..."; \
fi

rm -r $config_dir

echo "Remove /usr/local/lib/libquibble.so? [Y/n]"
read ans

if [ "$ans" = "n" ]; \
    then echo "/usr/local/lib/libquibble.so may still be in your system!"; \
    else echo "removing /usr/local/lib/libquibble.so!" ;sudo rm /usr/local/lib/libquibble.so;
fi

echo "done!"
